import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { headers } from 'next/headers'

import { getScriptNonceFromHeader } from './helper/get-script-nonce-from-header'
import Script from 'next/script'
const inter = Inter({ subsets: ['latin'] })

export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const contentSecurityPolicy: string | null = headers().get('Content-Security-Policy')
  const nonce = contentSecurityPolicy ? getScriptNonceFromHeader(contentSecurityPolicy) : undefined

  return (
    <html lang="en">
      <Script 
        src="https://www.googletagmanager.com/gtm.js?id=GTM-MP9KXF85"
        strategy="afterInteractive"
        nonce={nonce}
      />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
